// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZjn6bU4ZPzsHmLkMGdmebb2EzraTAvZY',
    appId: '1:161059394107:web:7751bad56aefe5d3f5821e',
    messagingSenderId: '161059394107',
    projectId: 'expense-tracker-dfb04',
    authDomain: 'expense-tracker-dfb04.firebaseapp.com',
    storageBucket: 'expense-tracker-dfb04.firebasestorage.app',
    measurementId: 'G-LBF930DS11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGKSXtq6Gafxkpu2PYWAHEKNn1v2M46RM',
    appId: '1:161059394107:android:d17f1f327e54c48df5821e',
    messagingSenderId: '161059394107',
    projectId: 'expense-tracker-dfb04',
    storageBucket: 'expense-tracker-dfb04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXe2NF9scli3g4Z72phEL8NLWzRlmkXDA',
    appId: '1:161059394107:ios:50210edbd1d91425f5821e',
    messagingSenderId: '161059394107',
    projectId: 'expense-tracker-dfb04',
    storageBucket: 'expense-tracker-dfb04.firebasestorage.app',
    iosBundleId: 'com.example.personalExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXe2NF9scli3g4Z72phEL8NLWzRlmkXDA',
    appId: '1:161059394107:ios:50210edbd1d91425f5821e',
    messagingSenderId: '161059394107',
    projectId: 'expense-tracker-dfb04',
    storageBucket: 'expense-tracker-dfb04.firebasestorage.app',
    iosBundleId: 'com.example.personalExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZjn6bU4ZPzsHmLkMGdmebb2EzraTAvZY',
    appId: '1:161059394107:web:0a3185d69edebbcdf5821e',
    messagingSenderId: '161059394107',
    projectId: 'expense-tracker-dfb04',
    authDomain: 'expense-tracker-dfb04.firebaseapp.com',
    storageBucket: 'expense-tracker-dfb04.firebasestorage.app',
    measurementId: 'G-7NTFEPCJVL',
  );
}
